name: Linux Flatpak Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08
      options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Flatpak Package
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: Scripta.flatpak
          manifest-path: linux/packaging/io.github.scripta.Scripta.json
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload Flatpak Artifact to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Scripta.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

